### ISSUE TITLE
[BETA] - App Sometimes Crashes When Quickly Applying Theme Multiple Times

### ISSUE THREAD

**Issue by bbmaster123** [ad2017gd/RainbowTaskbar#62]
very cool update! I'm very impressed by the ability to script full on animations to apply directly to the taskbar! Eventually I'd like to attempt to port this as a theme [Matrix](https://github.com/Rezmason/matrix/tree/simplified)

**EDIT: ahh I can just wrap it in an iframe! that's simple!**

I have a couple of other cool theme ideas as well that I hope to attempt soon.

In the meantime, I had been creating a much more generic matrix theme to test, and I notice the whole app crashes and exits if you quickly apply a theme multiple times in succession. Can be reproduced by either by applying the theme itself multiple times quickly, or clicking run from the editor. 

Event viewer logs a .net runtime error, and an app error:

```
Application: rnbtsk-x64.exe
CoreCLR Version: 8.0.1024.46610
.NET Version: 8.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AggregateException: One or more errors occurred. (Operation aborted (0x80004004 (E_ABORT)))
 ---> System.Runtime.InteropServices.COMException (0x80004004): Operation aborted (0x80004004 (E_ABORT))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2ControllerAsync(IntPtr ParentWindow)
   at Microsoft.Web.WebView2.Wpf.WebView2.Microsoft.Web.WebView2.Wpf.IWebView2Private.InitializeController(IntPtr parent_window, CoreWebView2ControllerOptions controllerOptions)
   at Microsoft.Web.WebView2.Wpf.WebView2Base.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RainbowTaskbar.Configuration.Web.WebConfig.<>c__DisplayClass6_0.<Stop>b__1()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at RainbowTaskbar.Configuration.Web.WebConfig.<>c.<<Stop>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at RainbowTaskbar.App.Main()
```

```
Faulting application name: rnbtsk-x64.exe, version: 2.99.0.0, time stamp: 0x66960000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4249, time stamp: 0x0cf64c6a
Exception code: 0xe0434352
Fault offset: 0x000000000005fe4c
Faulting process id: 0x0x18B0
Faulting application start time: 0x0x1DB1FDFD8C59CCA
Faulting application path: C:\Users\bbmaster123\Desktop\rnbtsk-x64.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: fc0bbe52-a0cf-454d-ba08-66874683f132
Faulting package full name: 
Faulting package-relative application ID: 
```
Windows 11 22631.4317

I do have other visual mods running, but this doesn't seem like a conflict to me. I'd guess input just needs to be blocked temporarily, until the theme is done applying.
  
I don't notice crashes anywhere else so far, whether within or outside of the program

thanks :D

**Comment by ad2017gd** [comment]
thanks for the report! i already caught this and fixed it, just didn't release it yet
